export const SELECTORS = {
  login: {
    emailInput: 'Email ID',
    passwordInput: 'Password',
    rememberCheckbox: 'Remember me',
    submitButton: 'Login Now',
    cookieAccept: 'Accept All',
    chatIframe: 'iframe[name="fc_widget"]',
    chatClose: 'Close Notifications',
  },
  projects: {
    navLink: 'Projects',
    createProjectBtn: 'Create Project',
    projectNameInput: 'Project Name',
    customFunnelCard: 'Custom Funnel A personalized',
    createBtn: 'Create',
  },
  pagesModal: {
    addPageSidebarBtn: 'Add New Page',
    pageNameInput: 'Enter Page name',
    pathInput: 'Enter Path',
    typeTrigger: 'Select a page type',
    typeTriggerAlt: '#page-type-button',
    types: {
      sales: 'Used to pitch or sell',
      checkout: 'Checkout Page',
      thankyou: 'Shown after successful',
    },
    addPageSubmitBtn: 'Add Page',
    useTemplateBtn: 'Use This Template',
  },
  products: {
    navLink: 'Products',
    createProductBtn: 'Create Product',
    digitalProductType: 'Digital Product Perfect for',
    continueBtn: 'Continue',
    productNameInput: 'e.g. Ultimate Marketing Course',
    uploadImageBox: 'Click to upload PNG, JPG up',
    galleryDialog: 'Image Gallery',
    continuePricingBtn: 'Continue to Pricing',
    addPricingBtn: 'Add Pricing',
    addPriceBtn: 'Add Price',
    oneTimeBtn: 'One-Time',
    saveAndContinueBtn: 'Save & Continue',
    priceInput: 'Price in INR',
    finishSetupBtn: 'Finish Setup',
    paymentPricingTab: 'Payment & Pricing',
    paymentProvidersTab: 'Payment Providers',
  },
  funnelBuilder: {
    navLink: 'Funnel',
    createFunnelBtn: 'Create New Funnel',
    funnelNameInput: 'Enter Funnel name',
    nextBtn: 'Next →',
    regularType: 'Normal Funnel Standard',
    oneClickType: 'One-Click Upsell Save payment',
    searchProductTrigger: 'Search and select a product...',
    productDropdownMenu: '.absolute.z-50',
    createFunnelSubmit: 'Create Funnel',
    addNextStepBtn: 'Add Next Step',
    continueToAddBtn: 'Continue to Add',
  },
  editor: {
    editPageLink: 'Edit Page',
    publishBtn: 'Publish Publish the page live.',
    publishAsSalesBtn: 'Publish as Sales Page',
    publishAsThankYouBtn: 'Publish as Thank You (',
    styleSettingsBtn: 'Style Settings',
    goToNextStepFunnel: 'Go To Next Step In Funnel',
    goToNextStepProduct: 'Go To Next Step In Product',
  },
  payment: {
    stripeCardFrame: 'iframe[name^="__privateStripeFrame"]',
    cardNumber: 'Card number',
    expiryDate: 'Expiry date',
    securityCode: 'Security code',
    completeOrderLink: 'Complete Order ',
  }
};